### ISSUE TITLE
Test statistic and p-value is NA

### ISSUE THREAD

**Issue by alvinwt** [armstrtw/rrcov#1]
Hi, I am trying to use the Wilk's test function on a matrix (600x96)

| sample | cohort | 1 | 2 | 3 |
| --- | --- | --- | --- | --- |
| X8012199 | X8012199 | Pancreas | 68 | 44 |
| X8012211 | X8012211 | Pancreas | 61 | 47 |
| X8012321 | X8012321 | Pancreas | 44 | 26 |
| X8012774 | X8012774 | Pancreas | 110 | 81 |
| X8013222 | X8013222 | Pancreas | 126 | 79 |
| X8013912 | X8013912 | Pancreas | 81 | 56 |

and I obtained the out put as below:

grp = as.factor(pan_cca_counts[,2])
mat = pan_cca_counts[,2:98]
test1 = Wilks.test(mat, grouping=grp, method="c")

data:  x
Wilks' Lambda = NaN, Chi2-Value = NaN, DF = 97, p-value = NA.

I am wondering what the NA means in this case, if it is the matrices are not significantly different, the p-value is very low or that data format might be wrong.

**Comment by armstrtw** [comment]
I think you should reach out to the author of this package for this question.  I wrote this version just to make the package faster (using TBB) since the original version is single threaded.

the original author is:
Author: Valentin Todorov valentin.todorov@chello.at

Happy to help w/ any questions regarding the parallel aspects of the package.

-Whit
